### ISSUE TITLE
Executable for macOS Catalina?

### ISSUE THREAD

**Issue by samueljoh** [adaskar/AggregateVolumeMenu#1]
Any chance you could make an executable that works under macOS Catalina as well? The one under "Releases" only works with macOS BigSur.

**Comment by adaskar** [comment]
I have uploaded the version 1.2, it should now be working in Catalina (10.10) and newer. 
Can you please try it?

**Comment by samueljoh** [comment]
Thanks a lot!! It runs perfectly on Catalina. 

There is however a problem with the menubar icon when using the light theme. It still shows a white icon on the white menubar making it hard to see.

**Comment by adaskar** [comment]
Yes i know that issue already just because i did not add a black icon. I'm closing that issue right now but if you create another one for the icon problem, i am going to solve that as well
